repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
    - id: check-added-large-files
    - id: trailing-whitespace
    - id: check-docstring-first
    - id: check-json
    - id: check-merge-conflict
    - id: check-xml
    - id: detect-private-key
    - id: mixed-line-ending
    - id: pretty-format-json
      args: [--autofix]
    - id: requirements-txt-fixer
- repo: https://github.com/psf/black
  rev: 20.8b1
  hooks:
  - id: black
    language_version: python38
    args: [ -l 119 ]
- repo: https://github.com/pycqa/isort
  rev: 5.6.4
  hooks:
  - id: isort
    args: ["--profile", "black"]
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.8.4
  hooks:
  - id: flake8
    additional_dependencies: [flake8-isort==4.0.0, flake8-quotes==3.0.0, flake8-print==3.1.4]
