version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  app:
    build: ..
    command: uvicorn src.database.app.main:app --host 0.0.0.0 --port 80
    environment:
      - REMOTE_DEBUG
    ports:
      - 8080:80
    depends_on:
      - db
