version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build: ..
    command: uvicorn src.database.main:app --host 0.0.0.0 --port 8000
    environment:
      - REMOTE_DEBUG
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
    ports:
      - 8080:8000
    depends_on:
      - db
  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080
    depends_on:
      - db

volumes:
  postgres_data:
