services:
  db:
    env_file:
      - envs/dev
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8090:8080
    depends_on:
      - db

  app:
    build:
      target: dev
    env_file:
      - envs/dev
    ports:
      - 8080:8000
    volumes:
      - ../src:/app/src

  ner:
    build:
      target: dev
