services:
  db:
    env_file:
      - envs/dev
    ports:
      - 5432:5432

  queue:
    image: rabbitmq:management
    env_file:
      - envs/dev
    ports:
      - 15672:15672

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8090:8080
    depends_on:
      - db

  app:
    build:
      target: dev
    env_file:
      - envs/dev
    ports:
      - 8080:8000
    volumes:
      - ../src/database:/app/src/database
      - ../src/config.py:/app/src/config.py
      - ../src/logger.py:/app/src/logger.py
      - ../src/loggers.conf:/app/src/loggers.conf

  ner:
    build:
      target: dev
    env_file:
      - envs/dev
    volumes:
      - ../src:/app/src

  words:
    build:
      target: dev
    env_file:
      - envs/dev
    volumes:
      - ../src:/app/src

  sentiment:
    build:
      target: dev
    env_file:
      - envs/dev
    volumes:
      - ../src:/app/src
