version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - postgres_data_diploma:/var/lib/postgresql/data

  app:
    build:
      context: ..
    environment:
      - REMOTE_DEBUG
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - 8080:8000
    depends_on:
      - db

volumes:
  postgres_data_diploma:
